# package(default_visibility = ["//visibility:public"])

# filegroup(
#     name = "proto_files",
#     srcs = glob([
#         "*.proto",
#     ]),
# )

# proto_library(
#     name = "protos",
#     srcs = [":proto_files"],
#     deps = [
#         # "@com_google_protobuf//:descriptor_proto",
#     ],
# )

# java_proto_library(
#     name =  "java_protos",
#     deps = [":protos"]
# )