package(default_visibility = ["//visibility:public"])

java_library(
    name = "fdb-sql-layer-core-protobuf",
    srcs = [
        "ProtobufDecompiler.java"
    ],
    deps = [
        "@protobuf//jar",
    ]
)