# package(default_visibility = ["//visibility:public"])

# filegroup(
#     name = "srcs",
#     srcs = ["BUILD"] + glob(["**/*.java"]),
# )

# java_library(
#     name = "fdb-sql-layer-core-qp-util",
#     srcs = [ ":srcs"],
# )