java_library(
    name = "fdb-sql-layer-routinefw",
    srcs = [
        "src/main/java/com/foundationdb/sql/routinefw/RoutineFirewall.java",
        "src/main/java/com/foundationdb/sql/routinefw/ShieldedInvokable.java",
    ],
)