# package(default_visibility = ["//visibility:public"])

# java_library(
#     name = "fdb-sql-layer-core-util-tuple",
#     srcs = [
#         "Tuple2.java",
#         "TupleFloatingUtil.java",
#     ],
# )